# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 13:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_q', '0008_auto_20160224_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duckling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_moderator', models.BooleanField(default=False)),
                ('wants_push', models.BooleanField(default=False)),
                ('notification_schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_q.Schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Quack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('has_been_processed', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Duckling')),
            ],
        ),
        migrations.AddField(
            model_name='duckling',
            name='quack_list',
            field=models.ManyToManyField(blank=True, to='api.Quack'),
        ),
        migrations.AddField(
            model_name='duckling',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
