# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 13:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170710_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duckling',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
